name: CD

on: 
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Bundle
      run: mkdir ./out && mkdir ./out/Yoga-travel-agency && cp -r css img icons js logo ./out/Yoga-travel-agency/ && cp index.html ./out/Yoga-travel-agency/
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.DEPLOY_TOKEN }}
        external_repository: MemboLembo/MemboLembo.github.io
        publish_dir: ./out
        publish_branch: master
        keep_files: true
